#!/usr/bin/env python3
"""One-shot: rebuild qs-analysis.db from library frontmatter + implication rows.

Stdlib only (csv, json, sqlite3, pathlib). From the repo root:

    python3 analysis/rebuild.py

If analysis/fragments/*.jsonl exist, they are merged into implication.csv first.
The .db is a local build artifact and is not committed.
"""

from __future__ import annotations

import csv
import sqlite3
import sys
from pathlib import Path

from merge_fragments import main as merge_fragments

ROOT = Path(__file__).resolve().parents[1]
LIBRARY = ROOT / "library"
ANALYSIS = Path(__file__).resolve().parent
SCHEMA = ANALYSIS / "schema.sql"
IMPLICATION_CSV = ANALYSIS / "implication.csv"
PREDICTED_CSV = ANALYSIS / "predicted_implication.csv"
DESIGN_CSV = ANALYSIS / "design.csv"
DESIGN_IMPLICATION_CSV = ANALYSIS / "design_implication.csv"
REQUIREMENT_CSV = ANALYSIS / "requirement.csv"
IMPLICATION_DESIGN_CSV = ANALYSIS / "implication_design.csv"
DESIGN_REQUIREMENT_CSV = ANALYSIS / "design_requirement.csv"
SEED_EFFECT = ANALYSIS / "seed_effect.sql"
DB_PATH = ROOT / "qs-analysis.db"

SKIP = {"INDEX.md", "README.md", "TAXONOMY.md", "_template.md"}

FAMILIES = {
    "collective-field-response",
    "latched-order",
    "gapped-coherence",
    "threshold-conversion",
    "lattice-modes",
    "ensemble-averages",
}
CONSTRAINT_TAGS = {
    "spatial-buffer",
    "clock-latency",
    "energy-barrier",
    "mechanical-lattice",
    "field-threshold",
    "thermal",
}


def parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        raise ValueError("missing frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError("unterminated frontmatter")
    data: dict = {}
    current_list = None
    for raw in parts[1].splitlines():
        line = raw.rstrip()
        if not line:
            continue
        if line.startswith("  - ") and current_list is not None:
            data[current_list].append(line[4:].strip())
            continue
        if ":" not in line or line.startswith(" "):
            current_list = None
            continue
        key, val = line.split(":", 1)
        key = key.strip()
        val = val.strip()
        if val == "":
            data[key] = []
            current_list = key
        else:
            data[key] = val
            current_list = None
    return data


def load_effects() -> tuple[list[dict], list[tuple[str, str]]]:
    effects = []
    constraints = []
    for path in sorted(LIBRARY.glob("*.md")):
        if path.name in SKIP:
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        slug = fm["id"]
        if slug != path.stem:
            raise SystemExit(f"{path.name}: id {slug!r} != filename stem")
        family = fm["family"]
        if family not in FAMILIES:
            raise SystemExit(f"{slug}: unknown family {family!r}")
        effects.append(
            {
                "slug": slug,
                "title": fm["title"],
                "family": family,
                "status": fm["status"],
                "confidence_data": fm["confidence_data"],
                "confidence_mapping": fm["confidence_mapping"],
                "source_path": f"library/{path.name}",
                "updated": fm["updated"],
            }
        )
        tags = fm.get("constraints") or []
        if isinstance(tags, str):
            tags = [tags]
        for tag in tags:
            if tag not in CONSTRAINT_TAGS:
                raise SystemExit(f"{slug}: unknown constraint tag {tag!r}")
            constraints.append((slug, tag))
    return effects, constraints


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_seed_effect(effects: list[dict], constraints: list[tuple[str, str]]) -> None:
    lines = [
        "-- Generated by rebuild.py from library/ frontmatter. Do not edit.",
        "BEGIN;",
        "DELETE FROM effect_constraint;",
        "DELETE FROM effect;",
    ]
    for e in effects:
        lines.append(
            "INSERT INTO effect (slug, title, family, status, confidence_data, "
            "confidence_mapping, source_path, updated) VALUES ({}, {}, {}, {}, {}, {}, {}, {});".format(
                sql_quote(e["slug"]),
                sql_quote(e["title"]),
                sql_quote(e["family"]),
                sql_quote(e["status"]),
                sql_quote(e["confidence_data"]),
                sql_quote(e["confidence_mapping"]),
                sql_quote(e["source_path"]),
                sql_quote(e["updated"]),
            )
        )
    for slug, tag in constraints:
        lines.append(
            "INSERT INTO effect_constraint (slug, tag) VALUES ({}, {});".format(
                sql_quote(slug), sql_quote(tag)
            )
        )
    lines.append("COMMIT;")
    lines.append("")
    SEED_EFFECT.write_text("\n".join(lines), encoding="utf-8")


def empty_to_none(value: str | None) -> str | None:
    if value is None:
        return None
    value = value.strip()
    return value if value else None


def load_table(path: Path, required: set[str], numeric: tuple[str, ...] = ()) -> list[dict]:
    if not path.exists():
        raise SystemExit(f"missing {path}")
    rows = []
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"{path.name} missing columns: {sorted(missing)}")
        for i, raw in enumerate(reader, start=2):
            row = {k: (v.strip() if isinstance(v, str) else v) for k, v in raw.items()}
            pk = next(iter(required))
            if not row.get(pk) and "impl_key" not in row:
                raise SystemExit(f"{path.name}:{i}: empty row")
            for key in numeric:
                val = empty_to_none(row.get(key))
                row[key] = float(val) if val not in (None, "") else None
            for key, val in list(row.items()):
                if key not in numeric and isinstance(val, str):
                    row[key] = empty_to_none(val) if key not in required else val
            rows.append(row)
    return rows


def load_implications() -> list[dict]:
    if not IMPLICATION_CSV.exists():
        raise SystemExit(f"missing {IMPLICATION_CSV}")
    rows = []
    with IMPLICATION_CSV.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        required = {
            "impl_key",
            "effect_slug",
            "source_path",
            "clause",
            "role",
            "aspect",
            "resource",
            "observed_text",
            "implied_text",
            "inference_kind",
            "description",
            "confidence",
            "updated",
        }
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"implication.csv missing columns: {sorted(missing)}")
        for i, raw in enumerate(reader, start=2):
            row = {k: (v.strip() if isinstance(v, str) else v) for k, v in raw.items()}
            if not row.get("impl_key"):
                raise SystemExit(f"implication.csv:{i}: empty impl_key")
            value_si = empty_to_none(row.get("value_si"))
            row["value_si"] = float(value_si) if value_si not in (None, "") else None
            for key in ("operator", "si_unit", "value_text", "notes"):
                row[key] = empty_to_none(row.get(key))
            row["origin"] = "extracted"
            rows.append(row)
    return rows


def load_predicted(effect_slugs: set[str]) -> list[dict]:
    if not PREDICTED_CSV.exists():
        return []
    rows = load_table(
        PREDICTED_CSV,
        {
            "impl_key",
            "clause",
            "role",
            "aspect",
            "resource",
            "observed_text",
            "implied_text",
            "inference_kind",
            "description",
            "confidence",
            "updated",
        },
        numeric=("value_si",),
    )
    out = []
    for i, row in enumerate(rows, start=2):
        key = row["impl_key"]
        if not key.startswith("predicted:"):
            raise SystemExit(f"predicted_implication.csv:{i}: impl_key must start with predicted:")
        slug = empty_to_none(row.get("effect_slug"))
        path = empty_to_none(row.get("source_path"))
        if slug and slug not in effect_slugs:
            raise SystemExit(f"{key}: unknown effect_slug {slug!r}")
        if slug and path != f"library/{slug}.md":
            path = f"library/{slug}.md"
        if not slug:
            path = None
        row["effect_slug"] = slug
        row["source_path"] = path
        row["origin"] = "predicted"
        out.append(row)
    return out


def maybe_merge_fragments() -> None:
    fragments = sorted((ANALYSIS / "fragments").glob("*.jsonl"))
    if not fragments:
        return
    merge_fragments()


def rebuild() -> int:
    maybe_merge_fragments()
    effects, constraints = load_effects()
    implications = load_implications()

    slugs = {e["slug"] for e in effects}
    predicted = load_predicted(slugs)
    keys = set()
    per_effect: dict[str, int] = {s: 0 for s in slugs}
    for row in implications:
        slug = row["effect_slug"]
        if slug not in slugs:
            raise SystemExit(f"{row['impl_key']}: unknown effect_slug {slug!r}")
        if row["impl_key"] in keys:
            raise SystemExit(f"duplicate impl_key {row['impl_key']!r}")
        keys.add(row["impl_key"])
        if not row["impl_key"].startswith(slug + ":"):
            raise SystemExit(
                f"{row['impl_key']}: impl_key must start with {slug}:"
            )
        if row["source_path"] != f"library/{slug}.md":
            raise SystemExit(
                f"{row['impl_key']}: source_path should be library/{slug}.md"
            )
        per_effect[slug] += 1

    for row in predicted:
        if row["impl_key"] in keys:
            raise SystemExit(f"duplicate impl_key {row['impl_key']!r}")
        keys.add(row["impl_key"])

    missing_effects = sorted(s for s, n in per_effect.items() if n == 0)
    if missing_effects:
        raise SystemExit(
            "no implication rows for: " + ", ".join(missing_effects)
        )

    designs = load_table(
        DESIGN_CSV,
        {
            "design_key",
            "title",
            "summary",
            "home_family",
            "status",
            "confidence",
            "description",
            "updated",
        },
    )
    requirements = load_table(
        REQUIREMENT_CSV,
        {
            "req_key",
            "title",
            "kind",
            "aspect",
            "resource",
            "statement",
            "status",
            "confidence",
            "updated",
        },
        numeric=("value_si",),
    )
    impl_designs = load_table(
        IMPLICATION_DESIGN_CSV,
        {"impl_key", "design_key", "membership"},
    )
    design_reqs = load_table(
        DESIGN_REQUIREMENT_CSV,
        {"design_key", "req_key", "strength"},
    )
    design_impls = load_table(
        DESIGN_IMPLICATION_CSV,
        {"design_key", "impl_key", "relation", "strength"},
    )

    design_keys = {r["design_key"] for r in designs}
    req_keys = {r["req_key"] for r in requirements}
    if len(design_keys) != len(designs):
        raise SystemExit("duplicate design_key")
    if len(req_keys) != len(requirements):
        raise SystemExit("duplicate req_key")

    predicted_keys = {r["impl_key"] for r in predicted}
    for row in impl_designs:
        if row["impl_key"] not in keys:
            raise SystemExit(f"implication_design: unknown impl_key {row['impl_key']!r}")
        if row["impl_key"] in predicted_keys:
            raise SystemExit(
                f"implication_design: predicted {row['impl_key']!r} cannot be evidence"
            )
        if row["design_key"] not in design_keys:
            raise SystemExit(f"implication_design: unknown design_key {row['design_key']!r}")
    for row in design_impls:
        if row["impl_key"] not in keys:
            raise SystemExit(f"design_implication: unknown impl_key {row['impl_key']!r}")
        if row["design_key"] not in design_keys:
            raise SystemExit(f"design_implication: unknown design_key {row['design_key']!r}")
        if row["impl_key"] in predicted_keys and row["relation"] != "predicts":
            raise SystemExit(
                f"design_implication: predicted {row['impl_key']!r} must use relation=predicts"
            )
    for row in design_reqs:
        if row["design_key"] not in design_keys:
            raise SystemExit(f"design_requirement: unknown design_key {row['design_key']!r}")
        if row["req_key"] not in req_keys:
            raise SystemExit(f"design_requirement: unknown req_key {row['req_key']!r}")

    reqs_with_design = {r["req_key"] for r in design_reqs}
    orphan_reqs = sorted(req_keys - reqs_with_design)
    if orphan_reqs:
        raise SystemExit("requirement with no design edge: " + ", ".join(orphan_reqs))

    write_seed_effect(effects, constraints)

    if DB_PATH.exists():
        DB_PATH.unlink()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(SCHEMA.read_text(encoding="utf-8"))

    conn.executemany(
        """
        INSERT INTO effect (
          slug, title, family, status, confidence_data,
          confidence_mapping, source_path, updated
        ) VALUES (
          :slug, :title, :family, :status, :confidence_data,
          :confidence_mapping, :source_path, :updated
        )
        """,
        effects,
    )
    conn.executemany(
        "INSERT INTO effect_constraint (slug, tag) VALUES (?, ?)",
        constraints,
    )
    conn.executemany(
        """
        INSERT INTO implication (
          impl_key, origin, effect_slug, source_path, clause, role, aspect, resource,
          observed_text, implied_text, inference_kind, description,
          operator, value_si, si_unit, value_text, confidence, notes, updated
        ) VALUES (
          :impl_key, :origin, :effect_slug, :source_path, :clause, :role, :aspect, :resource,
          :observed_text, :implied_text, :inference_kind, :description,
          :operator, :value_si, :si_unit, :value_text, :confidence, :notes, :updated
        )
        """,
        implications + predicted,
    )
    conn.executemany(
        """
        INSERT INTO design (
          design_key, title, summary, home_family, status, confidence,
          description, notes, updated
        ) VALUES (
          :design_key, :title, :summary, :home_family, :status, :confidence,
          :description, :notes, :updated
        )
        """,
        designs,
    )
    conn.executemany(
        """
        INSERT INTO requirement (
          req_key, title, kind, aspect, resource, statement,
          operator, value_si, si_unit, value_text, status, confidence, notes, updated
        ) VALUES (
          :req_key, :title, :kind, :aspect, :resource, :statement,
          :operator, :value_si, :si_unit, :value_text, :status, :confidence, :notes, :updated
        )
        """,
        requirements,
    )
    conn.executemany(
        """
        INSERT INTO implication_design (impl_key, design_key, membership, notes)
        VALUES (:impl_key, :design_key, :membership, :notes)
        """,
        impl_designs,
    )
    conn.executemany(
        """
        INSERT INTO design_requirement (design_key, req_key, strength, notes)
        VALUES (:design_key, :req_key, :strength, :notes)
        """,
        design_reqs,
    )
    conn.executemany(
        """
        INSERT INTO design_implication (design_key, impl_key, relation, strength, notes)
        VALUES (:design_key, :impl_key, :relation, :strength, :notes)
        """,
        design_impls,
    )
    conn.commit()

    n_effect = conn.execute("SELECT COUNT(*) FROM effect").fetchone()[0]
    n_impl = conn.execute("SELECT COUNT(*) FROM implication").fetchone()[0]
    n_open = conn.execute(
        "SELECT COUNT(*) FROM implication WHERE inference_kind = 'open' OR role = 'gap'"
    ).fetchone()[0]
    n_num = conn.execute(
        "SELECT COUNT(*) FROM implication WHERE value_si IS NOT NULL"
    ).fetchone()[0]
    n_design = conn.execute("SELECT COUNT(*) FROM design").fetchone()[0]
    n_req = conn.execute("SELECT COUNT(*) FROM requirement").fetchone()[0]
    n_id = conn.execute("SELECT COUNT(*) FROM implication_design").fetchone()[0]
    n_dr = conn.execute("SELECT COUNT(*) FROM design_requirement").fetchone()[0]
    n_di = conn.execute("SELECT COUNT(*) FROM design_implication").fetchone()[0]
    n_pred = conn.execute(
        "SELECT COUNT(*) FROM implication WHERE origin = 'predicted'"
    ).fetchone()[0]
    n_ext = n_impl - n_pred
    rel_counts = dict(
        conn.execute(
            "SELECT relation, COUNT(*) FROM design_implication GROUP BY relation"
        )
    )
    overlap = conn.execute(
        """
        SELECT COUNT(*) FROM implication_design id
        JOIN design_implication di
          ON di.impl_key = id.impl_key AND di.design_key = id.design_key
        """
    ).fetchone()[0]
    mapped = {
        r[0]
        for r in conn.execute("SELECT DISTINCT impl_key FROM implication_design")
    }
    unmapped = sorted((keys - predicted_keys) - mapped)
    designs_without_req = [
        r[0]
        for r in conn.execute(
            "SELECT design_key FROM design WHERE design_key NOT IN "
            "(SELECT design_key FROM design_requirement)"
        )
    ]
    designs_without_down = [
        r[0]
        for r in conn.execute(
            "SELECT design_key FROM design WHERE design_key NOT IN "
            "(SELECT design_key FROM design_implication)"
        )
    ]
    conn.close()

    print(f"wrote {DB_PATH}")
    print(f"  effect:              {n_effect}")
    print(f"  effect_constraint:   {len(constraints)}")
    print(f"  implication:         {n_impl} ({n_ext} extracted, {n_pred} predicted)")
    print(f"  with value_si:       {n_num}")
    print(f"  open or gap:         {n_open}")
    print(f"  design:              {n_design}")
    print(f"  requirement:         {n_req}")
    print(f"  implication_design:  {n_id}")
    print(f"  design_requirement:  {n_dr}")
    print(f"  design_implication:  {n_di}  {rel_counts}")
    print(f"  pairs in both junctions: {overlap}")
    print(f"  extracted implications unused as evidence: {len(unmapped)}")
    if designs_without_down:
        print("  warning: design with no downward edges:", ", ".join(designs_without_down))
    empty = [s for s, n in per_effect.items() if n < 4]
    if empty:
        print("  warning: fewer than 4 implication rows:", ", ".join(empty))
    if designs_without_req:
        print("  warning: design with no requirements:", ", ".join(designs_without_req))
    return 0


if __name__ == "__main__":
    sys.exit(rebuild())
