#!/usr/bin/env python3
"""Rebuild qs-analysis.db from library frontmatter + curated implication.csv."""

from __future__ import annotations

import csv
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LIBRARY = ROOT / "library"
ANALYSIS = Path(__file__).resolve().parent
SCHEMA = ANALYSIS / "schema.sql"
IMPLICATION_CSV = ANALYSIS / "implication.csv"
SEED_EFFECT = ANALYSIS / "seed_effect.sql"
DB_PATH = ROOT / "qs-analysis.db"

SKIP = {"INDEX.md", "README.md", "TAXONOMY.md", "_template.md"}

FAMILIES = {
    "collective-field-response",
    "latched-order",
    "gapped-coherence",
    "threshold-conversion",
    "lattice-modes",
    "ensemble-averages",
}
CONSTRAINT_TAGS = {
    "spatial-buffer",
    "clock-latency",
    "energy-barrier",
    "mechanical-lattice",
    "field-threshold",
    "thermal",
}


def parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        raise ValueError("missing frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError("unterminated frontmatter")
    data: dict = {}
    current_list = None
    for raw in parts[1].splitlines():
        line = raw.rstrip()
        if not line:
            continue
        if line.startswith("  - ") and current_list is not None:
            data[current_list].append(line[4:].strip())
            continue
        if ":" not in line or line.startswith(" "):
            current_list = None
            continue
        key, val = line.split(":", 1)
        key = key.strip()
        val = val.strip()
        if val == "":
            data[key] = []
            current_list = key
        else:
            data[key] = val
            current_list = None
    return data


def load_effects() -> tuple[list[dict], list[tuple[str, str]]]:
    effects = []
    constraints = []
    for path in sorted(LIBRARY.glob("*.md")):
        if path.name in SKIP:
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        slug = fm["id"]
        if slug != path.stem:
            raise SystemExit(f"{path.name}: id {slug!r} != filename stem")
        family = fm["family"]
        if family not in FAMILIES:
            raise SystemExit(f"{slug}: unknown family {family!r}")
        effects.append(
            {
                "slug": slug,
                "title": fm["title"],
                "family": family,
                "status": fm["status"],
                "confidence_data": fm["confidence_data"],
                "confidence_mapping": fm["confidence_mapping"],
                "source_path": f"library/{path.name}",
                "updated": fm["updated"],
            }
        )
        tags = fm.get("constraints") or []
        if isinstance(tags, str):
            tags = [tags]
        for tag in tags:
            if tag not in CONSTRAINT_TAGS:
                raise SystemExit(f"{slug}: unknown constraint tag {tag!r}")
            constraints.append((slug, tag))
    return effects, constraints


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_seed_effect(effects: list[dict], constraints: list[tuple[str, str]]) -> None:
    lines = [
        "-- Generated by rebuild.py from library/ frontmatter. Do not edit.",
        "BEGIN;",
        "DELETE FROM effect_constraint;",
        "DELETE FROM effect;",
    ]
    for e in effects:
        lines.append(
            "INSERT INTO effect (slug, title, family, status, confidence_data, "
            "confidence_mapping, source_path, updated) VALUES ({}, {}, {}, {}, {}, {}, {}, {});".format(
                sql_quote(e["slug"]),
                sql_quote(e["title"]),
                sql_quote(e["family"]),
                sql_quote(e["status"]),
                sql_quote(e["confidence_data"]),
                sql_quote(e["confidence_mapping"]),
                sql_quote(e["source_path"]),
                sql_quote(e["updated"]),
            )
        )
    for slug, tag in constraints:
        lines.append(
            "INSERT INTO effect_constraint (slug, tag) VALUES ({}, {});".format(
                sql_quote(slug), sql_quote(tag)
            )
        )
    lines.append("COMMIT;")
    lines.append("")
    SEED_EFFECT.write_text("\n".join(lines), encoding="utf-8")


def empty_to_none(value: str | None) -> str | None:
    if value is None:
        return None
    value = value.strip()
    return value if value else None


def load_implications() -> list[dict]:
    if not IMPLICATION_CSV.exists():
        raise SystemExit(f"missing {IMPLICATION_CSV}")
    rows = []
    with IMPLICATION_CSV.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        required = {
            "impl_key",
            "effect_slug",
            "source_path",
            "clause",
            "role",
            "aspect",
            "resource",
            "observed_text",
            "implied_text",
            "inference_kind",
            "description",
            "confidence",
            "updated",
        }
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"implication.csv missing columns: {sorted(missing)}")
        for i, raw in enumerate(reader, start=2):
            row = {k: (v.strip() if isinstance(v, str) else v) for k, v in raw.items()}
            if not row.get("impl_key"):
                raise SystemExit(f"implication.csv:{i}: empty impl_key")
            value_si = empty_to_none(row.get("value_si"))
            row["value_si"] = float(value_si) if value_si not in (None, "") else None
            for key in ("operator", "si_unit", "value_text", "notes"):
                row[key] = empty_to_none(row.get(key))
            rows.append(row)
    return rows


def rebuild() -> int:
    effects, constraints = load_effects()
    implications = load_implications()

    slugs = {e["slug"] for e in effects}
    keys = set()
    per_effect: dict[str, int] = {s: 0 for s in slugs}
    for row in implications:
        slug = row["effect_slug"]
        if slug not in slugs:
            raise SystemExit(f"{row['impl_key']}: unknown effect_slug {slug!r}")
        if row["impl_key"] in keys:
            raise SystemExit(f"duplicate impl_key {row['impl_key']!r}")
        keys.add(row["impl_key"])
        if not row["impl_key"].startswith(slug + ":"):
            raise SystemExit(
                f"{row['impl_key']}: impl_key must start with {slug}:"
            )
        if row["source_path"] != f"library/{slug}.md":
            raise SystemExit(
                f"{row['impl_key']}: source_path should be library/{slug}.md"
            )
        per_effect[slug] += 1

    missing_effects = sorted(s for s, n in per_effect.items() if n == 0)
    if missing_effects:
        raise SystemExit(
            "no implication rows for: " + ", ".join(missing_effects)
        )

    write_seed_effect(effects, constraints)

    if DB_PATH.exists():
        DB_PATH.unlink()
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(SCHEMA.read_text(encoding="utf-8"))

    conn.executemany(
        """
        INSERT INTO effect (
          slug, title, family, status, confidence_data,
          confidence_mapping, source_path, updated
        ) VALUES (
          :slug, :title, :family, :status, :confidence_data,
          :confidence_mapping, :source_path, :updated
        )
        """,
        effects,
    )
    conn.executemany(
        "INSERT INTO effect_constraint (slug, tag) VALUES (?, ?)",
        constraints,
    )
    conn.executemany(
        """
        INSERT INTO implication (
          impl_key, effect_slug, source_path, clause, role, aspect, resource,
          observed_text, implied_text, inference_kind, description,
          operator, value_si, si_unit, value_text, confidence, notes, updated
        ) VALUES (
          :impl_key, :effect_slug, :source_path, :clause, :role, :aspect, :resource,
          :observed_text, :implied_text, :inference_kind, :description,
          :operator, :value_si, :si_unit, :value_text, :confidence, :notes, :updated
        )
        """,
        implications,
    )
    conn.commit()

    n_effect = conn.execute("SELECT COUNT(*) FROM effect").fetchone()[0]
    n_impl = conn.execute("SELECT COUNT(*) FROM implication").fetchone()[0]
    n_open = conn.execute(
        "SELECT COUNT(*) FROM implication WHERE inference_kind = 'open' OR role = 'gap'"
    ).fetchone()[0]
    n_num = conn.execute(
        "SELECT COUNT(*) FROM implication WHERE value_si IS NOT NULL"
    ).fetchone()[0]
    conn.close()

    print(f"wrote {DB_PATH}")
    print(f"  effect:            {n_effect}")
    print(f"  effect_constraint: {len(constraints)}")
    print(f"  implication:       {n_impl}")
    print(f"  with value_si:     {n_num}")
    print(f"  open or gap:       {n_open}")
    empty = [s for s, n in per_effect.items() if n < 4]
    if empty:
        print("  warning: fewer than 4 rows:", ", ".join(empty))
    return 0


if __name__ == "__main__":
    sys.exit(rebuild())
